apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: jai-enterprise
type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: enterprise_db
  MYSQL_USER: enterprise_user
  MYSQL_PASSWORD: enterprise123

